In [5]:
import numpy as np

array1 = np.array([1,2,3,4])

lista1 = [1,2,3,4]

print(f"Array: {array1}")
print(f"Lista: {lista1}")

# indexera arrays, fungerar på samma sätt som att indexera listor []
print(array1[2])

# multiplicera alla tal med 2
array2 = array1*2
print(array2)

lista2 = lista1*2
print(lista2)

kvadrater = array1**2
print(kvadrater)

Array: [1 2 3 4]
Lista: [1, 2, 3, 4]
3
[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]
[ 1  4  9 16]


In [12]:
# 1

import numpy as np 

tal = np.arange(11)

print(tal)

tal1 = np.arange(-10,11)

print(tal1)

[ 0  1  2  3  4  5  6  7  8  9 10]
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9  10]


In [ ]:
# 2

import numpy as np 

array = np.array(10, 20, 30, 40, 50, 60, 70, 80, 90, 100)

array1= array*10

print()